// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_Lozgar.DTO;

#nullable disable

namespace back_Lozgar.Migrations
{
    [DbContext(typeof(appDBcontext))]
    [Migration("20241029173307_InitDBDos")]
    partial class InitDBDos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_Lozgar.Model.BoletosCliente", b =>
                {
                    b.Property<int>("ID_boletos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_boletos"));

                    b.Property<string>("DescripcionViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinoCuidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiaViaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraLlegada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraSalida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPasajero")
                        .HasColumnType("int");

                    b.Property<int>("IdViajesDisponible")
                        .HasColumnType("int");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenCuidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefonoPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_boletos");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("back_Lozgar.Model.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<string>("Nombre_pasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPasajeros")
                        .HasColumnType("int");

                    b.Property<DateTime>("diaViaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("telefono_pasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("back_Lozgar.Model.Conductor", b =>
                {
                    b.Property<int>("id_conductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_conductor"));

                    b.Property<string>("Nombre_conductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_conductor");

                    b.ToTable("Conductor");
                });

            modelBuilder.Entity("back_Lozgar.Model.ViajeClientes", b =>
                {
                    b.Property<int>("Id_ViajeClientes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ViajeClientes"));

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_ViajeDisponible")
                        .HasColumnType("int");

                    b.Property<int>("id_conductor")
                        .HasColumnType("int");

                    b.HasKey("Id_ViajeClientes");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("id_ViajeDisponible");

                    b.HasIndex("id_conductor");

                    b.ToTable("ViajeClientes");
                });

            modelBuilder.Entity("back_Lozgar.Model.ViajesDisponibles", b =>
                {
                    b.Property<int>("id_ViajeDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_ViajeDisponible"));

                    b.Property<string>("HoraLlegada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraSalida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destino_cuidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("origen_cuidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("id_ViajeDisponible");

                    b.ToTable("ViajesDisponible");
                });

            modelBuilder.Entity("back_Lozgar.Model.ViajeClientes", b =>
                {
                    b.HasOne("back_Lozgar.Model.Cliente", "clientes")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_Lozgar.Model.ViajesDisponibles", "viajesdisponibles")
                        .WithMany()
                        .HasForeignKey("id_ViajeDisponible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_Lozgar.Model.Conductor", "conductores")
                        .WithMany()
                        .HasForeignKey("id_conductor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clientes");

                    b.Navigation("conductores");

                    b.Navigation("viajesdisponibles");
                });
#pragma warning restore 612, 618
        }
    }
}
